version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=i4JE57KO9FH!
      - MYSQL_HOST=db
      - MYSQL_USER=Fares
      - MYSQL_PASSWORD=i4JE57KO9FH!
      - MYSQL_DB=school_intranet
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=dossoufares@gmail.com
      - MAIL_PASSWORD=avoc cvcu vsyo bzqo
      - MAIL_DEFAULT_SENDER=dossoufares@gmail.com
    depends_on:
      - db
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: python app.py

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=i4JE57KO9FH!
      - MYSQL_DATABASE=school_intranet
      - MYSQL_USER=Fares
      - MYSQL_PASSWORD=i4JE57KO9FH!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=Fares
      - PMA_PASSWORD=i4JE57KO9FH!
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:

